name: Execute Terraform commands
author: Abhinav Khanna
description: Execute Terraform commands using Terraform CLI
inputs: 
  command:
    description: Terraform Command to execute
    required: True
  params:
    description: input to the Terraform command
    required: False
outputs:
  commandOutput:
    description: std output from the Terraform commands
  commandError:
    description: std error from the Terraform commands
  
runs:
  using: 'node12'
  main:  'dist/index.js'

branding:
  icon: 'globe'  
  color: 'red'