name: A workflow to execute Terraform commands
on: push
jobs:
  build:
    name: Execute Terraform Commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v1
      - name: Call Terraform Action
        id: tf1
        uses: "./"
        with:
            command: version
      - name: Call Terraform Action
        id: tf2
        uses: "./"
        with:
            command: init
            params: '{"dir":  "./tf"}'
      
      - name: Call Terraform Action
        id: tf3
        uses: "./"
        with:
            command: plan
            params: '{"dir":  "./tf", "compactWarnings" : true, "detailedExitCode": true, "lock": false}'
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
            
