name: A workflow to execute Terraform commands
on: push
jobs:
  build:
    name: Execute Terraform Commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v1
      - name: Call Terraform Action
        id: tf1
        uses: "./"
        with:
            command: version
      - name: Call Terraform Action Init
        id: tf2
        uses: "./"
        with:
            command: init
            params: |
              {
                "cwd":  "./tf",
                "noColor" : false,
                "upgrade": false
              }
        
      
      - name: Call Terraform Action Plan
        id: tf3
        uses: "./"
        with:
            command: plan
            params: |
              { 
                "var" :{
                  "github_token": "${{ secrets.access_token }}"
                },
                "out" : "tf.plan.json",
                "cwd" : "./tf"
              }
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
      
      - name: Call Terraform Action Apply
        id: tf4
        uses: "./"
        with:
            command: apply
            params:  | 
              {
                "dirOrPlan":  "tf.plan.json",
                "cwd": "./tf"
              }
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}