name: A workflow to execute Terraform commands
on: push
jobs:
  build:
    name: Execute Terraform Commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v1
      - name: Call Terraform Action
        id: tf1
        uses: "./"
        with:
            command: version
      - name: Call Terraform Action
        id: tf2
        uses: "./"
        with:
            command: init
            params: '{"dir":  "C:\Users\abhin\tf"}'
      
      - name: Call Terraform Action
        id: tf3
        uses: "./"
        with:
            command: plan
            params: '{"dir":  "C:\Users\abhin\tf", "compactWarnings" : true, "detailedExitCode": true, "lock", false}'
            
