name: Terraform Commands
on: push
jobs:
  build:
    name: Execute Terraform Commands
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Files
        uses: actions/checkout@v1
      
      - name: Call Terraform Action
        id: tfDownload
        uses: "./"
        with:
            command: download
            params: |
              {
                "version" : "0.11.15-oci"
              }

      - name: Call Terraform Action
        id: tfVersion
        uses: "./"
        with:
            command: version
      - name: Call Terraform Action Init
        id: tfInit
        uses: "./"
        with:
            command: init
            params: |
              {
                "cwd":  "./tf",
                "noColor" : false,
                "upgrade": false
              }
        
      
      - name: Call Terraform Action Plan
        id: tfPlan
        uses: "./"
        with:
            command: plan
            params: |
              { 
                "var" :{
                  "github_token": "${{ secrets.access_token }}",
                  "repo_name": "Random-repo-${{ github.run_id }}"
                },
                "out" : "tf.plan",
                "cwd" : "./tf",
                "upload": true,
                "artifactName": "planFile",
                "continueOnError": true
              }
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
      

      - name: Call Terraform Action Show
        id: tfShow1
        uses: "./"
        with:
            command: show
            params: |
              { 
               
                "path" : "tf.plan",
                "cwd" : "./tf",
                "upload": true,
                "artifactName": "planFileText",
                "continueOnError": false,
                "fileName": "planfile.txt"
              }
      
      - name: Call Terraform Action Show
        id: tfShow2
        uses: "./"
        with:
            command: show
            params: |
              { 
               
                "path" : "tf.plan",
                "json": true,
                "cwd" : "./tf",
                "upload": true,
                "artifactName": "planFileJson",
                "continueOnError": false,
                "fileName": "planfile.json"
              }
      - name: Call Terraform Action Apply
        id: tfApply
        uses: "./"
        with:
            command: apply
            params:  | 
              {
                "dirOrPlan":  "tf.plan.json",
                "cwd": "./tf"
              }
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}