name: A workflow to execute Terraform commands
on: push
jobs:
  build:
    name: Execute Terraform Commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v1
      - name: Call Terraform Action
        id: tf1
        uses: "./"
        with:
            command: version
            params: '{"a": 1, "b": "2"}'
      - name: Call Terraform Action
        id: tf1
        uses: "./"
        with:
            command: plan
            params: '{"a": 1, "b": "2"}'
      
      - name: Call Terraform Action
        id: tf1
        uses: "./"
        with:
            command: apply
            params: '{"a": 1, "b": "2"}'
            
